
/*
    Current HL7 Standard Code Set
    Vaccines Administered in the United States
    http://www2a.cdc.gov/vaccines/iis/iisstandards/vaccines.asp?rpt=cvx
*/

CREATE TABLE VaccinationKind (
    VaccinationKindID int          PRIMARY KEY,
    CVXCode           int          NOT NULL,
    Status            varchar(20)  NOT NULL,
    DateUpdated       date         NOT NULL,
    VaccinationName   varchar(100) NOT NULL,
    VaccinationDesc   varchar(250) NOT NULL,
    Notes             varchar(500)
);

INSERT INTO VaccinationKind VALUES (001, 143, 'Active'      , '2011-3-20' , 'Adenovirus types 4 and 7', 'Adenovirus, type 4 and type 7, live, oral', 'This vaccine is administered as 2 tablets.');
INSERT INTO VaccinationKind VALUES (002,  54, 'Inactive'    , '2010-5-28' , 'adenovirus, type 4', 'adenovirus vaccine, type 4, live, oral', '');
INSERT INTO VaccinationKind VALUES (003,  55, 'Inactive'    , '2010-5-28' , 'adenovirus, type 7', 'adenovirus vaccine, type 7, live, oral', '');
INSERT INTO VaccinationKind VALUES (004,  82, 'Inactive'    , '2010-9-30' , 'adenovirus, unspecified formulation', 'adenovirus vaccine, unspecified formulation', 'This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a adenovirus vaccination when noted on a vaccination card)');
INSERT INTO VaccinationKind VALUES (005,  24, 'Active'      , '2010-5-28' , 'anthrax', 'anthrax vaccine', '');
INSERT INTO VaccinationKind VALUES (006, 801, 'Active'      , '2014-2-7'  , 'AS03 Adjuvant', 'AS03 Adjuvant', 'This is the adjuvant that is packaged with H5N1 vaccine, adjuvanted');
INSERT INTO VaccinationKind VALUES (007,  19, 'Active'      , '2010-5-28' , 'BCG', 'Bacillus Calmette-Guerin vaccine', '');
INSERT INTO VaccinationKind VALUES (008,  27, 'Active'      , '2010-5-28' , 'botulinum antitoxin', 'botulinum antitoxin', '');
INSERT INTO VaccinationKind VALUES (009,  26, 'Inactive'    , '2010-5-28' , 'cholera', 'cholera vaccine', '');
INSERT INTO VaccinationKind VALUES (010,  29, 'Active'      , '2010-5-28' , 'CMVIG', 'cytomegalovirus immune globulin, intravenous', '');
INSERT INTO VaccinationKind VALUES (011,  56, 'Never Active', '2010-5-28' , 'dengue fever', 'dengue fever vaccine', '');
INSERT INTO VaccinationKind VALUES (012,  12, 'Active'      , '2010-5-28' , 'diphtheria antitoxin', 'diphtheria antitoxin', '');
INSERT INTO VaccinationKind VALUES (013,  28, 'Active'      , '2010-5-28' , 'DT (pediatric)', 'diphtheria and tetanus toxoids, adsorbed for pediatric use', '');
INSERT INTO VaccinationKind VALUES (014,  20, 'Active'      , '2010-5-28' , 'DTaP', 'diphtheria, tetanus toxoids and acellular pertussis vaccine', '');
INSERT INTO VaccinationKind VALUES (015, 106, 'Active'      , '2010-5-28' , 'DTaP, 5 pertussis antigens', 'diphtheria, tetanus toxoids and acellular pertussis vaccine, 5 pertussis antigens', '');
INSERT INTO VaccinationKind VALUES (016, 107, 'Inactive'    , '2010-9-30' , 'DTaP, unspecified formulation', 'diphtheria, tetanus toxoids and acellular pertussis vaccine, unspecified formulation', 'This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a DTaP vaccination when noted on a vaccination card)');
INSERT INTO VaccinationKind VALUES (017, 146, 'Pending'     , '2011-8-31' , 'DTaP,IPV,Hib,HepB', 'Diphtheria and Tetanus Toxoids and Acellular Pertussis Adsorbed, Inactivated Poliovirus, Haemophilus b Conjugate (Meningococcal Outer Membrane Protein Complex), and Hepatitis B (Recombinant) Vaccine.', 'Note that this vaccine is different from CVX 132.');
INSERT INTO VaccinationKind VALUES (018, 110, 'Active'      , '2010-5-28' , 'DTaP-Hep B-IPV', 'DTaP-hepatitis B and poliovirus vaccine', '');
INSERT INTO VaccinationKind VALUES (019,  50, 'Active'      , '2010-5-28' , 'DTaP-Hib', 'DTaP-Haemophilus influenzae type b conjugate vaccine', '');
INSERT INTO VaccinationKind VALUES (020, 120, 'Active'      , '2010-5-28' , 'DTaP-Hib-IPV', 'diphtheria, tetanus toxoids and acellular pertussis vaccine, Haemophilus influenzae type b conjugate, and poliovirus vaccine, inactivated (DTaP-Hib-IPV)', '');
INSERT INTO VaccinationKind VALUES (021, 130, 'Active'      , '2010-5-28' , 'DTaP-IPV', 'Diphtheria, tetanus toxoids and acellular pertussis vaccine, and poliovirus vaccine, inactivated', '');
INSERT INTO VaccinationKind VALUES (022, 132, 'Inactive'    , '2010-5-28' , 'DTaP-IPV-HIB-HEP B, historical', 'Historical record of vaccine containing * diphtheria, tetanus toxoids and acellular pertussis, * poliovirus, inactivated, * Haemophilus influenzae type b conjugate, * Hepatitis B (DTaP-Hib-IPV)', 'This is not the same as CVX 146, Hexavalent vaccine.');
INSERT INTO VaccinationKind VALUES (023, 102, 'Inactive'    , '2014-5-30' , 'DTaP/DTP-Hib-Hep B', 'DTP- Haemophilus influenzae type b conjugate and hepatitis b vaccine', 'This non-US vaccine contained DTP prior to 2007 and now contains DTaP');
INSERT INTO VaccinationKind VALUES (024,  01, 'Inactive'    , '2010-5-28' , 'DTP', 'diphtheria, tetanus toxoids and pertussis vaccine', '');
INSERT INTO VaccinationKind VALUES (025,  22, 'Inactive'    , '2010-5-28' , 'DTP-Hib', 'DTP-Haemophilus influenzae type b conjugate vaccine', '');
INSERT INTO VaccinationKind VALUES (026,  57, 'Never Active', '2010-5-28' , 'hantavirus', 'hantavirus vaccine', '');
INSERT INTO VaccinationKind VALUES (027,  30, 'Active'      , '2010-5-28' , 'HBIG', 'hepatitis B immune globulin', '');
INSERT INTO VaccinationKind VALUES (028,  52, 'Active'      , '2010-5-28' , 'Hep A, adult', 'hepatitis A vaccine, adult dosage', '');
INSERT INTO VaccinationKind VALUES (029, 154, 'Never Active', '2013-4-1'  , 'Hep A, IG', 'Hepatitis A immune globulin', 'Do not use this code. This product may be used for Hep A and other viral infections. The correct vaccine / CVX is 86 (IG).');
INSERT INTO VaccinationKind VALUES (030,  83, 'Active'      , '2010-5-28' , 'Hep A, ped/adol, 2 dose', 'hepatitis A vaccine, pediatric/adolescent dosage, 2 dose schedule', '');
INSERT INTO VaccinationKind VALUES (031,  84, 'Inactive'    , '2010-5-28' , 'Hep A, ped/adol, 3 dose', 'hepatitis A vaccine, pediatric/adolescent dosage, 3 dose schedule', 'This vaccine formulation is inactive and should not be used, except to record historic vaccinations with this formulation.');
INSERT INTO VaccinationKind VALUES (032,  31, 'Inactive'    , '2010-9-30' , 'Hep A, pediatric, unspecified formulation', 'hepatitis A vaccine, pediatric dosage, unspecified formulation', 'Do NOT use this code. If formulation is unknown, use CVX 85. There is only one formulation of Hep A, peds.');
INSERT INTO VaccinationKind VALUES (033,  85, 'Inactive'    , '2010-9-30' , 'Hep A, unspecified formulation', 'hepatitis A vaccine, unspecified formulation', 'This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a HepA vaccination when noted on a vaccination card)');
INSERT INTO VaccinationKind VALUES (034, 104, 'Active'      , '2010-5-28' , 'Hep A-Hep B', 'hepatitis A and hepatitis B vaccine', '');
INSERT INTO VaccinationKind VALUES (035,  08, 'Active'      , '2010-5-28' , 'Hep B, adolescent or pediatric', 'hepatitis B vaccine, pediatric or pediatric/adolescent dosage', 'This code applies to any standard pediatric formulation of Hepatitis B vaccine. It should not be used for the 2-dose hepatitis B schedule for adolescents (11-15 year olds). It requires Merck''s Recombivax HB® adult formulation. Use code 43 for that vaccine.');
INSERT INTO VaccinationKind VALUES (036,  42, 'Inactive'    , '2010-5-28' , 'Hep B, adolescent/high risk infant', 'hepatitis B vaccine, adolescent/high risk infant dosage', 'As of August 27, 1998, Merck ceased distribution of their adolescent/high risk infant hepatitis B vaccine dosage. Code 42 should only be used to record historical records. For current administration of hepatitis B vaccine, pediatric/adolescent dosage, use code 08.');
INSERT INTO VaccinationKind VALUES (037,  43, 'Active'      , '2010-5-28' , 'Hep B, adult', 'hepatitis B vaccine, adult dosage', 'As of September 1999, a 2-dose hepatitis B schedule for adolescents (11-15 year olds) was FDA approved for Merck''s Recombivax HB® adult formulation. Use code 43 for the 2-dose. This code should be used for any use of standard adult formulation of hepatitis B vaccine.');
INSERT INTO VaccinationKind VALUES (038,  44, 'Active'      , '2010-5-28' , 'Hep B, dialysis', 'hepatitis B vaccine, dialysis patient dosage', '');
INSERT INTO VaccinationKind VALUES (039,  45, 'Inactive'    , '2010-9-30' , 'Hep B, unspecified formulation', 'hepatitis B vaccine, unspecified formulation', 'This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a HepB vaccination when noted on a vaccination card)');
INSERT INTO VaccinationKind VALUES (040,  58, 'Never Active', '2010-5-28' , 'Hep C', 'hepatitis C vaccine', '');
INSERT INTO VaccinationKind VALUES (041,  59, 'Never Active', '2010-5-28' , 'Hep E', 'hepatitis E vaccine', '');
INSERT INTO VaccinationKind VALUES (042,  60, 'Never Active', '2010-5-28' , 'herpes simplex 2', 'herpes simplex virus, type 2 vaccine', '');
INSERT INTO VaccinationKind VALUES (043,  47, 'Inactive'    , '2010-5-28' , 'Hib (HbOC)', 'Haemophilus influenzae type b vaccine, HbOC conjugate', '');
INSERT INTO VaccinationKind VALUES (044,  46, 'Inactive'    , '2010-5-28' , 'Hib (PRP-D)', 'Haemophilus influenzae type b vaccine, PRP-D conjugate', '');
INSERT INTO VaccinationKind VALUES (045,  49, 'Active'      , '2010-5-28' , 'Hib (PRP-OMP)', 'Haemophilus influenzae type b vaccine, PRP-OMP conjugate', '');
INSERT INTO VaccinationKind VALUES (046,  48, 'Active'      , '2010-5-28' , 'Hib (PRP-T)', 'Haemophilus influenzae type b vaccine, PRP-T conjugate', '');
INSERT INTO VaccinationKind VALUES (047,  17, 'Inactive'    , '2010-9-30' , 'Hib, unspecified formulation', 'Haemophilus influenzae type b vaccine, conjugate unspecified formulation', '');
INSERT INTO VaccinationKind VALUES (048,  51, 'Active'      , '2010-5-28' , 'Hib-Hep B', 'Haemophilus influenzae type b conjugate and Hepatitis B vaccine', '');
INSERT INTO VaccinationKind VALUES (049,  61, 'Never Active', '2010-5-28' , 'HIV', 'human immunodeficiency virus vaccine', '');
INSERT INTO VaccinationKind VALUES (050, 118, 'Active'      , '2010-5-28' , 'HPV, bivalent', 'human papilloma virus vaccine, bivalent', '');
INSERT INTO VaccinationKind VALUES (051,  62, 'Active'      , '2010-5-28' , 'HPV, quadrivalent', 'human papilloma virus vaccine, quadrivalent', '');
INSERT INTO VaccinationKind VALUES (052, 137, 'Inactive'    , '2010-9-30' , 'HPV, unspecified formulation', 'HPV, unspecified formulation', 'This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a HPV vaccination when noted on a vaccination card)');
INSERT INTO VaccinationKind VALUES (053, 165, 'Active'      , '2014-12-11', 'HPV9', 'Human Papillomavirus 9-valent vaccine', '');
INSERT INTO VaccinationKind VALUES (054,  86, 'Active'      , '2010-5-28' , 'IG', 'immune globulin, intramuscular', '');
INSERT INTO VaccinationKind VALUES (055,  14, 'Inactive'    , '2010-9-30' , 'IG, unspecified formulation', 'immune globulin, unspecified formulation', '');
INSERT INTO VaccinationKind VALUES (056,  87, 'Active'      , '2010-5-28' , 'IGIV', 'immune globulin, intravenous', '');
INSERT INTO VaccinationKind VALUES (057, 160, 'Active'      , '2014-5-27' , 'Influenza A monovalent (H5N1), ADJUVANTED-2013', 'Influenza A monovalent (H5N1), adjuvanted, National stockpile 2013', 'Approved by FDA 2013, adjuvant is mixed at point of administration.');
INSERT INTO VaccinationKind VALUES (058, 151, 'Inactive'    , '2013-1-28' , 'influenza nasal, unspecified formulation', 'influenza nasal, unspecified formulation', 'This CVX should only be used for historical records where the formulation of nasal flu vaccine is not known.');
INSERT INTO VaccinationKind VALUES (059, 123, 'Inactive'    , '2010-5-28' , 'influenza, H5N1-1203', 'influenza virus vaccine, H5N1, A/Vietnam/1203/2004 (national stockpile)', '');
INSERT INTO VaccinationKind VALUES (060, 135, 'Active'      , '2010-5-28' , 'Influenza, high dose seasonal', 'influenza, high dose seasonal, preservative-free', '');
INSERT INTO VaccinationKind VALUES (061, 153, 'Active'      , '2013-7-17' , 'Influenza, injectable, MDCK, preservative free', 'Influenza, injectable, Madin Darby Canine Kidney, preservative free', 'ccIIV3');
INSERT INTO VaccinationKind VALUES (062, 158, 'Active'      , '2013-8-20' , 'influenza, injectable, quadrivalent', 'influenza, injectable, quadrivalent, contains preservative', 'New in 2013. IIV4');
INSERT INTO VaccinationKind VALUES (063, 150, 'Active'      , '2013-7-17' , 'influenza, injectable, quadrivalent, preservative free', 'Influenza, injectable, quadrivalent, preservative free', 'New in 2012. IIV4');
INSERT INTO VaccinationKind VALUES (064, 161, 'Active'      , '2014-7-23' , 'Influenza, injectable,quadrivalent, preservative free, pediatric', 'Influenza, injectable,quadrivalent, preservative free, pediatric', '');
INSERT INTO VaccinationKind VALUES (065, 166, 'Active'      , '2014-12-15', 'influenza, intradermal, quadrivalent, preservative free', 'influenza, intradermal, quadrivalent, preservative free, injectable', '');
INSERT INTO VaccinationKind VALUES (066, 111, 'Inactive'    , '2014-9-22' , 'influenza, live, intranasal', 'influenza virus vaccine, live, attenuated, for intranasal use', 'LAIV3');
INSERT INTO VaccinationKind VALUES (067, 149, 'Active'      , '2013-7-17' , 'influenza, live, intranasal, quadrivalent', 'influenza, live, intranasal, quadrivalent', 'new in 2012. LAIV4');
INSERT INTO VaccinationKind VALUES (068, 155, 'Active'      , '2013-7-17' , 'influenza, recombinant, injectable, preservative free', 'Seasonal, trivalent, recombinant, injectable influenza vaccine, preservative free', 'RIV');
INSERT INTO VaccinationKind VALUES (069, 141, 'Active'      , '2013-7-17' , 'Influenza, seasonal, injectable', 'Influenza, seasonal, injectable', 'IIV3. This is one of two codes replacing CVX 15, which is being retired.');
INSERT INTO VaccinationKind VALUES (070, 140, 'Active'      , '2013-7-17' , 'Influenza, seasonal, injectable, preservative free', 'Influenza, seasonal, injectable, preservative free', 'IIV3. This vaccine code is one of two which replace CVX 15, influenza, split virus.');
INSERT INTO VaccinationKind VALUES (071, 144, 'Active'      , '2013-7-17' , 'influenza, seasonal, intradermal, preservative free', 'seasonal influenza, intradermal, preservative free', 'IIV3');
INSERT INTO VaccinationKind VALUES (072,  15, 'Inactive'    , '2010-9-30' , 'influenza, split (incl. purified surface antigen)', 'influenza virus vaccine, split virus (incl. purified surface antigen)-retired CODE', 'This code is being retired. It will still be found in older immunization records. It included both preservative free and non-preservative free.');
INSERT INTO VaccinationKind VALUES (073,  88, 'Inactive'    , '2010-9-30' , 'influenza, unspecified formulation', 'influenza virus vaccine, unspecified formulation', 'This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a Influenza vaccination when noted on a vaccination card)');
INSERT INTO VaccinationKind VALUES (074,  16, 'Inactive'    , '2010-5-28' , 'influenza, whole', 'influenza virus vaccine, whole virus', '');
INSERT INTO VaccinationKind VALUES (075,  10, 'Active'      , '2010-5-28' , 'IPV', 'poliovirus vaccine, inactivated', '');
INSERT INTO VaccinationKind VALUES (076, 134, 'Active'      , '2010-5-28' , 'Japanese Encephalitis IM', 'Japanese Encephalitis vaccine for intramuscular administration', '');
INSERT INTO VaccinationKind VALUES (077,  39, 'Active'      , '2010-5-28' , 'Japanese encephalitis SC', 'Japanese Encephalitis Vaccine SC', '');
INSERT INTO VaccinationKind VALUES (078, 129, 'Inactive'    , '2010-9-30' , 'Japanese Encephalitis, unspecified formulation', 'Japanese Encephalitis vaccine, unspecified formulation', 'This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a JE vaccination when noted on a vaccination card)');
INSERT INTO VaccinationKind VALUES (079,  63, 'Never Active', '2010-5-28' , 'Junin virus', 'Junin virus vaccine', '');
INSERT INTO VaccinationKind VALUES (080,  64, 'Never Active', '2010-5-28' , 'leishmaniasis', 'leishmaniasis vaccine', '');
INSERT INTO VaccinationKind VALUES (081,  65, 'Never Active', '2010-5-28' , 'leprosy', 'leprosy vaccine', '');
INSERT INTO VaccinationKind VALUES (082,  66, 'Inactive'    , '2010-5-28' , 'Lyme disease', 'Lyme disease vaccine', '');
INSERT INTO VaccinationKind VALUES (083,  04, 'Inactive'    , '2010-5-28' , 'M/R', 'measles and rubella virus vaccine', '');
INSERT INTO VaccinationKind VALUES (084,  67, 'Never Active', '2010-5-28' , 'malaria', 'malaria vaccine', '');
INSERT INTO VaccinationKind VALUES (085,  05, 'Inactive'    , '2010-8-31' , 'measles', 'measles virus vaccine', '');
INSERT INTO VaccinationKind VALUES (086,  68, 'Never Active', '2010-5-28' , 'melanoma', 'melanoma vaccine', '');
INSERT INTO VaccinationKind VALUES (087, 163, 'Active'      , '2015-2-2'  , 'meningococcal B, OMV', 'meningococcal B vaccine, recombinant, OMV, adjuvanted', '');
INSERT INTO VaccinationKind VALUES (088, 162, 'Active'      , '2014-11-3' , 'meningococcal B, recombinant', 'meningococcal B vaccine, fully recombinant', '');
INSERT INTO VaccinationKind VALUES (089, 164, 'Inactive'    , '2014-11-3' , 'meningococcal B, unspecified', 'meningococcal B, unspecified formulation', '');
INSERT INTO VaccinationKind VALUES (090, 103, 'Inactive'    , '2010-5-28' , 'meningococcal C conjugate', 'meningococcal C conjugate vaccine', '');
INSERT INTO VaccinationKind VALUES (091, 148, 'Active'      , '2012-7-11' , 'Meningococcal C/Y-HIB PRP', 'Meningococcal Groups C and Y and Haemophilus b Tetanus Toxoid Conjugate Vaccine', '');
INSERT INTO VaccinationKind VALUES (092, 147, 'Inactive'    , '2012-2-8'  , 'meningococcal MCV4, unspecified formulation', 'Meningococcal, MCV4, unspecified formulation(groups A, C, Y and W-135)', 'This CVX should only be used for historical doses of meningococcal conjugate vaccine where the formulation is unknown (oligosaccharide vs polysaccharide). It is not the same as CVX 108, Meningococcal, unspecified formulation.');
INSERT INTO VaccinationKind VALUES (093, 136, 'Active'      , '2010-5-28' , 'Meningococcal MCV4O', 'meningococcal oligosaccharide (groups A, C, Y and W-135) diphtheria toxoid conjugate vaccine (MCV4O)', '');
INSERT INTO VaccinationKind VALUES (094, 114, 'Active'      , '2010-5-28' , 'meningococcal MCV4P', 'meningococcal polysaccharide (groups A, C, Y and W-135) diphtheria toxoid conjugate vaccine (MCV4P)', '');
INSERT INTO VaccinationKind VALUES (095,  32, 'Active'      , '2010-5-28' , 'meningococcal MPSV4', 'meningococcal polysaccharide vaccine (MPSV4)', '');
INSERT INTO VaccinationKind VALUES (096, 108, 'Inactive'    , '2010-9-30' , 'meningococcal, unspecified formulation', 'meningococcal vaccine, unspecified formulation', 'This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a meningococcal vaccination when noted on a vaccination card)');
INSERT INTO VaccinationKind VALUES (097,  03, 'Active'      , '2010-5-28' , 'MMR', 'measles, mumps and rubella virus vaccine', '');
INSERT INTO VaccinationKind VALUES (098,  94, 'Active'      , '2010-5-28' , 'MMRV', 'measles, mumps, rubella, and varicella virus vaccine', '');
INSERT INTO VaccinationKind VALUES (099,  07, 'Active'      , '2010-5-28' , 'mumps', 'mumps virus vaccine', '');
INSERT INTO VaccinationKind VALUES (100, 127, 'Inactive'    , '2010-8-28' , 'Novel influenza-H1N1-09', 'Novel influenza-H1N1-09, injectable', '');
INSERT INTO VaccinationKind VALUES (101, 128, 'Inactive'    , '2010-8-28' , 'Novel Influenza-H1N1-09, all formulations', 'Novel influenza-H1N1-09, all formulations', 'This code is used whenever the actual formulation is not determined or when aggregating all Novel H1N1 Influenza-09 immunizations for reporting to CRA. It should not be used for seasonal influenza vaccine that is not otherwise specified. (NOS)');
INSERT INTO VaccinationKind VALUES (102, 125, 'Inactive'    , '2010-8-28' , 'Novel Influenza-H1N1-09, nasal', 'Novel Influenza-H1N1-09, live virus for nasal administration', '');
INSERT INTO VaccinationKind VALUES (103, 126, 'Inactive'    , '2010-8-28' , 'Novel influenza-H1N1-09, preservative-free', 'Novel influenza-H1N1-09, preservative-free, injectable', '');
INSERT INTO VaccinationKind VALUES (104,  02, 'Inactive'    , '2010-5-28' , 'OPV', 'poliovirus vaccine, live, oral', '');
INSERT INTO VaccinationKind VALUES (105,  69, 'Inactive'    , '2010-5-28' , 'parainfluenza-3', 'parainfluenza-3 virus vaccine', '');
INSERT INTO VaccinationKind VALUES (106,  11, 'Inactive'    , '2010-5-28' , 'pertussis', 'pertussis vaccine', '');
INSERT INTO VaccinationKind VALUES (107,  23, 'Active'      , '2010-5-28' , 'plague', 'plague vaccine', '');
INSERT INTO VaccinationKind VALUES (108, 133, 'Active'      , '2010-5-28' , 'Pneumococcal conjugate PCV 13', 'pneumococcal conjugate vaccine, 13 valent', '');
INSERT INTO VaccinationKind VALUES (109, 100, 'Inactive'    , '2014-6-26' , 'pneumococcal conjugate PCV 7', 'pneumococcal conjugate vaccine, 7 valent', '');
INSERT INTO VaccinationKind VALUES (110, 152, 'Inactive'    , '2013-1-28' , 'Pneumococcal Conjugate, unspecified formulation', 'Pneumococcal Conjugate, unspecified formulation', 'This CVX should only be used for historical records where the formulation of pneumococcal conjugate vaccine is not known.');
INSERT INTO VaccinationKind VALUES (111,  33, 'Active'      , '2010-5-28' , 'pneumococcal polysaccharide PPV23', 'pneumococcal polysaccharide vaccine, 23 valent', '');
INSERT INTO VaccinationKind VALUES (112, 109, 'Inactive'    , '2010-9-30' , 'pneumococcal, unspecified formulation', 'pneumococcal vaccine, unspecified formulation', 'This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a pneumococcal vaccination when noted on a vaccination card)');
INSERT INTO VaccinationKind VALUES (113,  89, 'Inactive'    , '2010-9-30' , 'polio, unspecified formulation', 'poliovirus vaccine, unspecified formulation', 'This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a polio vaccination when noted on a vaccination card)');
INSERT INTO VaccinationKind VALUES (114,  70, 'Never Active', '2010-5-28' , 'Q fever', 'Q fever vaccine', '');
INSERT INTO VaccinationKind VALUES (115,  40, 'Active'      , '2010-5-28' , 'rabies, intradermal injection', 'rabies vaccine, for intradermal injection', '');
INSERT INTO VaccinationKind VALUES (116,  18, 'Active'      , '2010-5-28' , 'rabies, intramuscular injection', 'rabies vaccine, for intramuscular injection', '');
INSERT INTO VaccinationKind VALUES (117,  90, 'Inactive'    , '2010-9-30' , 'rabies, unspecified formulation', 'rabies vaccine, unspecified formulation', 'This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a rabies vaccination when noted on a vaccination card)');
INSERT INTO VaccinationKind VALUES (118,  72, 'Never Active', '2010-5-28' , 'rheumatic fever', 'rheumatic fever vaccine', '');
INSERT INTO VaccinationKind VALUES (119, 159, 'Inactive'    , '2013-9-5'  , 'Rho(D) - Unspecified formulation', 'Rho(D) Unspecified formulation', '');
INSERT INTO VaccinationKind VALUES (120, 157, 'Active'      , '2013-8-13' , 'Rho(D) -IG IM', 'Rho(D) Immune globulin - IM', 'This immune globulin may be administered IM only.');
INSERT INTO VaccinationKind VALUES (121, 156, 'Active'      , '2013-7-26' , 'Rho(D)-IG', 'Rho(D) Immune globulin- IV or IM', 'This immune globulin may be administered either IM or IV.');
INSERT INTO VaccinationKind VALUES (122,  73, 'Never Active', '2010-5-28' , 'Rift Valley fever', 'Rift Valley fever vaccine', '');
INSERT INTO VaccinationKind VALUES (123,  34, 'Active'      , '2010-5-28' , 'RIG', 'rabies immune globulin', '');
INSERT INTO VaccinationKind VALUES (124, 119, 'Active'      , '2010-5-28' , 'rotavirus, monovalent', 'rotavirus, live, monovalent vaccine', '');
INSERT INTO VaccinationKind VALUES (125, 116, 'Active'      , '2010-5-28' , 'rotavirus, pentavalent', 'rotavirus, live, pentavalent vaccine', '');
INSERT INTO VaccinationKind VALUES (126,  74, 'Inactive'    , '2010-5-28' , 'rotavirus, tetravalent', 'rotavirus, live, tetravalent vaccine', '');
INSERT INTO VaccinationKind VALUES (127, 122, 'Inactive'    , '2010-9-30' , 'rotavirus, unspecified formulation', 'rotavirus vaccine, unspecified formulation', '');
INSERT INTO VaccinationKind VALUES (128,  71, 'Active'      , '2010-5-28' , 'RSV-IGIV', 'respiratory syncytial virus immune globulin, intravenous', '');
INSERT INTO VaccinationKind VALUES (129,  93, 'Active'      , '2010-5-28' , 'RSV-MAb', 'respiratory syncytial virus monoclonal antibody (palivizumab), intramuscular', '');
INSERT INTO VaccinationKind VALUES (130, 145, 'Pending'     , '2011-8-31' , 'RSV-MAb (new)', 'respiratory syncytial virus monoclonal antibody (motavizumab), intramuscular', '');
INSERT INTO VaccinationKind VALUES (131,  06, 'Active'      , '2010-5-28' , 'rubella', 'rubella virus vaccine', '');
INSERT INTO VaccinationKind VALUES (132,  38, 'Inactive'    , '2010-5-28' , 'rubella/mumps', 'rubella and mumps virus vaccine', '');
INSERT INTO VaccinationKind VALUES (133,  76, 'Inactive'    , '2010-5-28' , 'Staphylococcus bacterio lysate', 'Staphylococcus bacteriophage lysate', '');
INSERT INTO VaccinationKind VALUES (134, 138, 'Active'      , '2010-9-30' , 'Td (adult)', 'tetanus and diphtheria toxoids, not adsorbed, for adult use', 'Note that this Td is not adsorbed.');
INSERT INTO VaccinationKind VALUES (135, 113, 'Active'      , '2010-9-30' , 'Td (adult) preservative free', 'tetanus and diphtheria toxoids, adsorbed, preservative free, for adult use', '');
INSERT INTO VaccinationKind VALUES (136,  09, 'Active'      , '2010-8-20' , 'Td (adult), adsorbed', 'tetanus and diphtheria toxoids, adsorbed, for adult use', 'Note that this vaccine name has changed. See also Td (adult). It is not adsorbed.');
INSERT INTO VaccinationKind VALUES (137, 139, 'Inactive'    , '2010-9-30' , 'Td(adult) unspecified formulation', 'Td(adult) unspecified formulation', 'This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a Td vaccination when noted on a vaccination card)');
INSERT INTO VaccinationKind VALUES (138, 115, 'Active'      , '2010-5-28' , 'Tdap', 'tetanus toxoid, reduced diphtheria toxoid, and acellular pertussis vaccine, adsorbed', '');
INSERT INTO VaccinationKind VALUES (139,  35, 'Active'      , '2011-2-14' , 'tetanus toxoid, adsorbed', 'tetanus toxoid, adsorbed', '');
INSERT INTO VaccinationKind VALUES (140, 142, 'Active'      , '2011-2-14' , 'tetanus toxoid, not adsorbed', 'tetanus toxoid, not adsorbed', '');
INSERT INTO VaccinationKind VALUES (141, 112, 'Inactive'    , '2010-9-30' , 'tetanus toxoid, unspecified formulation', 'tetanus toxoid, unspecified formulation', '');
INSERT INTO VaccinationKind VALUES (142,  77, 'Inactive'    , '2010-5-28' , 'tick-borne encephalitis', 'tick-borne encephalitis vaccine', '');
INSERT INTO VaccinationKind VALUES (143,  13, 'Active'      , '2010-5-28' , 'TIG', 'tetanus immune globulin', '');
INSERT INTO VaccinationKind VALUES (144,  98, 'Inactive'    , '2010-9-30' , 'TST, unspecified formulation', 'tuberculin skin test; unspecified formulation', 'TB Skin test is not vaccine.');
INSERT INTO VaccinationKind VALUES (145,  95, 'Inactive'    , '2010-5-28' , 'TST-OT tine test', 'tuberculin skin test; old tuberculin, multipuncture device', 'TB Skin test is not vaccine.');
INSERT INTO VaccinationKind VALUES (146,  96, 'Inactive'    , '2010-5-28' , 'TST-PPD intradermal', 'tuberculin skin test; purified protein derivative solution, intradermal', 'TB Skin test is not vaccine.');
INSERT INTO VaccinationKind VALUES (147,  97, 'Inactive'    , '2010-5-28' , 'TST-PPD tine test', 'tuberculin skin test; purified protein derivative, multipuncture device', 'TB Skin test is not vaccine.');
INSERT INTO VaccinationKind VALUES (148,  78, 'Inactive'    , '2010-5-28' , 'tularemia vaccine', 'tularemia vaccine', '');
INSERT INTO VaccinationKind VALUES (149,  25, 'Active'      , '2010-5-28' , 'typhoid, oral', 'typhoid vaccine, live, oral', '');
INSERT INTO VaccinationKind VALUES (150,  41, 'Active'      , '2010-5-28' , 'typhoid, parenteral', 'typhoid vaccine, parenteral, other than acetone-killed, dried', '');
INSERT INTO VaccinationKind VALUES (151,  53, 'Active'      , '2010-5-28' , 'typhoid, parenteral, AKD (U.S. military)', 'typhoid vaccine, parenteral, acetone-killed, dried (U.S. military)', '');
INSERT INTO VaccinationKind VALUES (152,  91, 'Inactive'    , '2010-9-30' , 'typhoid, unspecified formulation', 'typhoid vaccine, unspecified formulation', 'This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a typhoid vaccination when noted on a vaccination card)');
INSERT INTO VaccinationKind VALUES (153, 101, 'Active'      , '2010-5-28' , 'typhoid, ViCPs', 'typhoid Vi capsular polysaccharide vaccine', '');
INSERT INTO VaccinationKind VALUES (154, 131, 'Inactive'    , '2010-5-28' , 'typhus, historical', 'Historical record of a typhus vaccination', '');
INSERT INTO VaccinationKind VALUES (155,  75, 'Active'      , '2010-5-28' , 'vaccinia (smallpox)', 'vaccinia (smallpox) vaccine', '');
INSERT INTO VaccinationKind VALUES (156, 105, 'Inactive'    , '2010-5-28' , 'vaccinia (smallpox) diluted', 'vaccinia (smallpox) vaccine, diluted', '');
INSERT INTO VaccinationKind VALUES (157,  79, 'Active'      , '2010-5-28' , 'vaccinia immune globulin', 'vaccinia immune globulin', '');
INSERT INTO VaccinationKind VALUES (158,  21, 'Active'      , '2010-5-28' , 'varicella', 'varicella virus vaccine', '');
INSERT INTO VaccinationKind VALUES (159,  81, 'Inactive'    , '2010-5-28' , 'VEE, inactivated', 'Venezuelan equine encephalitis, inactivated', '');
INSERT INTO VaccinationKind VALUES (160,  80, 'Inactive'    , '2010-5-28' , 'VEE, live', 'Venezuelan equine encephalitis, live, attenuated', '');
INSERT INTO VaccinationKind VALUES (161,  92, 'Inactive'    , '2010-9-30' , 'VEE, unspecified formulation', 'Venezuelan equine encephalitis vaccine, unspecified formulation', 'This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a VEE vaccination when noted on a vaccination card)');
INSERT INTO VaccinationKind VALUES (162,  36, 'Active'      , '2010-5-28' , 'VZIG', 'varicella zoster immune globulin', '');
INSERT INTO VaccinationKind VALUES (163, 117, 'Inactive'    , '2010-5-28' , 'VZIG (IND)', 'varicella zoster immune globulin (Investigational New Drug)', '');
INSERT INTO VaccinationKind VALUES (164,  37, 'Active'      , '2010-5-28' , 'yellow fever', 'yellow fever vaccine', '');
INSERT INTO VaccinationKind VALUES (165, 121, 'Active'      , '2010-5-28' , 'zoster', 'zoster vaccine, live', '');
INSERT INTO VaccinationKind VALUES (166, 998, 'Inactive'    , '2010-5-28' , 'no vaccine administered', 'no vaccine administered', 'Code 998 was added for use in VXU HL7 messages where the OBX segment is nested with the RXA segment, but the message does not contain information about a vaccine administration. An example of this use is to report the vaccines due next for a patient when no vaccine administration is being reported.');
INSERT INTO VaccinationKind VALUES (167,  99, 'Inactive'    , '2010-5-28' , 'RESERVED - do not use', 'RESERVED - do not use', 'Code 99 will not be used in this table to avoid confusion with code 999.');
INSERT INTO VaccinationKind VALUES (168, 999, 'Inactive'    , '2010-5-28' , 'unknown', 'unknown vaccine or immune globulin', 'This CVX code has little utility and should rarely be used.');
